module.exports = {
    INVALID_SESSION: 'INVALID_SESSION',
    INVALID_REQUEST: 'INVALID_REQUEST',
    IMAGE_VALIDATION_FAILED: 'IMAGE_VALIDATION_FAILED',
    IMAGE_LIMIT_EXCEEDED: 'IMAGE_LIMIT_EXCEEDED',
    IMAGE_UPLOAD_FAILED: 'IMAGE_UPLOAD_FAILED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    USER_BANNED: 'USER_BANNED',
    UNAUTHORIZED: 'UNAUTHORIZED',
    PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',
    THREAD_BODY_TOO_LONG: 'THREAD_BODY_TOO_LONG',
    THREAD_BODY_TOO_SHORT: 'THREAD_BODY_TOO_SHORT',
    THREAD_TITLE_INVALID: 'THREAD_TITLE_INVALID',
    COMMENT_BODY_TOO_LONG: 'COMMENT_BODY_TOO_LONG',
    COMMENT_BODY_TOO_SHORT: 'COMMENT_BODY_TOO_SHORT'
}